
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'F5520628987FDCBBDFE22D14A01B3C31'
    
_lr_action_items = {'GO':([0,],[2,]),'ASK':([0,],[3,]),'KICK':([0,],[4,]),'$end':([1,3,4,5,7,8,9,10,11,12,13,14,15,16,17,],[0,-13,-14,-1,-5,-6,-7,-8,-4,-9,-10,-11,-12,-3,-2,]),'NUMBER':([2,5,7,8,9,10,12,13,14,15,],[11,11,-5,-6,-7,-8,-9,-10,-11,-12,]),'LEFT':([2,6,11,],[12,12,-4,]),'RIGHT':([2,6,11,],[13,13,-4,]),'TOP':([2,6,11,],[14,14,-4,]),'DOWN':([2,6,11,],[15,15,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),'direction':([2,6,],[5,17,]),'num':([2,5,],[6,16,]),'left':([2,6,],[7,7,]),'right':([2,6,],[8,8,]),'top':([2,6,],[9,9,]),'down':([2,6,],[10,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> GO direction','expression',2,'p_move','Parser.py',71),
  ('expression -> GO num direction','expression',3,'p_move','Parser.py',72),
  ('expression -> GO direction num','expression',3,'p_move','Parser.py',73),
  ('num -> NUMBER','num',1,'p_num','Parser.py',91),
  ('direction -> left','direction',1,'p_direction','Parser.py',95),
  ('direction -> right','direction',1,'p_direction','Parser.py',96),
  ('direction -> top','direction',1,'p_direction','Parser.py',97),
  ('direction -> down','direction',1,'p_direction','Parser.py',98),
  ('left -> LEFT','left',1,'p_left','Parser.py',101),
  ('right -> RIGHT','right',1,'p_right','Parser.py',106),
  ('top -> TOP','top',1,'p_top','Parser.py',110),
  ('down -> DOWN','down',1,'p_down','Parser.py',114),
  ('expression -> ASK','expression',1,'p_expression_ask','Parser.py',118),
  ('expression -> KICK','expression',1,'p_expression_kick','Parser.py',122),
]
